version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: >
      sh -c " sleep 5 &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn gitinfodjango.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db