# Generated by Django 2.1.3 on 2018-12-05 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=100)),
                ('add', models.IntegerField()),
                ('sub', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='commiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Commiter'),
        ),
    ]
