# Generated by Django 2.1.4 on 2018-12-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181206_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='churn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
