# Generated by Django 2.1.4 on 2018-12-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commit_churn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commiter',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
