# Generated by Django 2.1.4 on 2018-12-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181211_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='date',
            field=models.DateTimeField(default='1990-01-01 09:30'),
        ),
    ]
