# Generated by Django 2.1.4 on 2018-12-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_commiterrortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, unique=True)),
                ('dependency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependency_repository', to='core.Repository')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_repository', to='core.Repository')),
            ],
        ),
    ]
