# Generated by Django 2.1.4 on 2018-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_submodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodule',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
