# Generated by Django 2.1.4 on 2018-12-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181227_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='char_add',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='char_churn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='char_sub',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
