# Generated by Django 2.1.4 on 2019-01-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_commitsmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitsmetrics',
            old_name='char_sum',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='commitsmetrics',
            old_name='sum',
            new_name='char_add',
        ),
    ]
