# Generated by Django 2.1.4 on 2019-01-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitsmetrics',
            name='tags',
            field=models.IntegerField(default=0),
        ),
    ]
