# Generated by Django 2.1.4 on 2019-01-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_commitsmetrics_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitsmetrics',
            name='repositories',
            field=models.IntegerField(default=0),
        ),
    ]
