# Generated by Django 2.1.4 on 2019-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_commitsmetrics_repositories'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='branch',
            field=models.CharField(default='master', max_length=256),
        ),
    ]
