# Generated by Django 2.1.4 on 2019-01-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190123_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitBlamePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Commit')),
                ('commiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Commiter')),
            ],
        ),
    ]
