# Generated by Django 2.1.4 on 2019-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190409_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitsmetrics',
            name='commits',
            field=models.IntegerField(default=0),
        ),
    ]
